// Calm, dual-palette theme configuration - Premium color system
// 70% neutral background | 20% soft color | 10% accent
// Soft pastels (light) | Muted deep tones (dark)

export const themeConfig = {
  default: {
    name: 'Default',
    light: {
      primary: '#5B8DEF',
      accent: '#E8EEF8',
      background: '#F8FAFC',
      text: '#334155',
      gradient: 'from-slate-50 to-blue-50',
      border: '#E2E8F0',
    },
    dark: {
      primary: '#7C9BED',
      accent: '#1E293B',
      background: '#0F172A',
      text: '#E2E8F0',
      gradient: 'from-slate-900 to-slate-800',
      border: '#334155',
    },
  },
  studies: {
    name: 'Studies',
    light: {
      primary: '#6B8BD4',
      accent: '#EEF2F9',
      background: '#F8FAFC',
      text: '#334155',
      gradient: 'from-slate-50 to-blue-50',
      border: '#E2E8F0',
    },
    dark: {
      primary: '#7C9BED',
      accent: '#1E293B',
      background: '#0F172A',
      text: '#E2E8F0',
      gradient: 'from-slate-900 to-slate-800',
      border: '#334155',
    },
  },
  work: {
    name: 'Work',
    light: {
      primary: '#8B7DB8',
      accent: '#F3F1F8',
      background: '#FAF9FC',
      text: '#3730A3',
      gradient: 'from-slate-50 to-violet-50',
      border: '#E9E5F0',
    },
    dark: {
      primary: '#9F8FCF',
      accent: '#211E2E',
      background: '#13111B',
      text: '#E9E5F5',
      gradient: 'from-slate-900 to-violet-950',
      border: '#2E2A3A',
    },
  },
  workout: {
    name: 'Workout',
    light: {
      primary: '#C99A6B',
      accent: '#FDF6F0',
      background: '#FFFAF7',
      text: '#5C4033',
      gradient: 'from-stone-50 to-amber-50',
      border: '#EDE6E0',
    },
    dark: {
      primary: '#D4A574',
      accent: '#2A2119',
      background: '#1A1612',
      text: '#F5EBE0',
      gradient: 'from-stone-900 to-amber-950',
      border: '#3D3428',
    },
  },
  health: {
    name: 'Health',
    light: {
      primary: '#6B9B8A',
      accent: '#F0F7F4',
      background: '#F8FCFA',
      text: '#2D4A3E',
      gradient: 'from-slate-50 to-emerald-50',
      border: '#DCE8E3',
    },
    dark: {
      primary: '#7DB39D',
      accent: '#1A2E28',
      background: '#0F1C18',
      text: '#D1E8DF',
      gradient: 'from-slate-900 to-emerald-950',
      border: '#2D453C',
    },
  },
  meditation: {
    name: 'Meditation',
    light: {
      primary: '#6B9A9A',
      accent: '#EFF7F7',
      background: '#F7FCFC',
      text: '#2D4545',
      gradient: 'from-slate-50 to-cyan-50',
      border: '#D9E8E8',
    },
    dark: {
      primary: '#7DB5B5',
      accent: '#1C2E2E',
      background: '#0F1C1C',
      text: '#D4ECEC',
      gradient: 'from-slate-900 to-cyan-950',
      border: '#2A3D3D',
    },
  },
  skillimprovement: {
    name: 'Skill Improvement',
    light: {
      primary: '#7B7FC4',
      accent: '#F0F0F8',
      background: '#F8F8FC',
      text: '#373B5C',
      gradient: 'from-slate-50 to-indigo-50',
      border: '#E3E4F0',
    },
    dark: {
      primary: '#8F93D4',
      accent: '#1F2035',
      background: '#12131F',
      text: '#E4E5F5',
      gradient: 'from-slate-900 to-indigo-950',
      border: '#2E2F45',
    },
  },
  reading: {
    name: 'Reading',
    light: {
      primary: '#6B8FB8',
      accent: '#EEF4FA',
      background: '#F7FAFD',
      text: '#2D3D52',
      gradient: 'from-slate-50 to-sky-50',
      border: '#DCE6F0',
    },
    dark: {
      primary: '#7DA5D4',
      accent: '#1C2D3D',
      background: '#0F1925',
      text: '#DCE9F5',
      gradient: 'from-slate-900 to-sky-950',
      border: '#2A3D52',
    },
  },
  creative: {
    name: 'Creative',
    light: {
      primary: '#B87B8A',
      accent: '#FBF3F5',
      background: '#FDF8F9',
      text: '#4A2D35',
      gradient: 'from-slate-50 to-rose-50',
      border: '#EDE0E3',
    },
    dark: {
      primary: '#C995A3',
      accent: '#2D1F24',
      background: '#1A1215',
      text: '#F5E4E8',
      gradient: 'from-slate-900 to-rose-950',
      border: '#3D2A30',
    },
  },
  wellness: {
    name: 'Wellness',
    light: {
      primary: '#B87A9E',
      accent: '#FBF3F9',
      background: '#FDF8FC',
      text: '#4A2D42',
      gradient: 'from-slate-50 to-pink-50',
      border: '#EDE0E8',
    },
    dark: {
      primary: '#CB9AB5',
      accent: '#2D1F28',
      background: '#1A1218',
      text: '#F5E4EF',
      gradient: 'from-slate-900 to-pink-950',
      border: '#3D2A38',
    },
  },
  personaldevelopment: {
    name: 'Personal Development',
    light: {
      primary: '#9A7FB8',
      accent: '#F5F0FA',
      background: '#FAF8FC',
      text: '#3D2D52',
      gradient: 'from-slate-50 to-violet-50',
      border: '#E8E0F0',
    },
    dark: {
      primary: '#B09AD4',
      accent: '#221E2E',
      background: '#13111B',
      text: '#EDE5F8',
      gradient: 'from-slate-900 to-violet-950',
      border: '#322E45',
    },
  },
  sociallife: {
    name: 'Social Life',
    light: {
      primary: '#B8A06B',
      accent: '#FAF8F0',
      background: '#FCFAF5',
      text: '#4A4230',
      gradient: 'from-slate-50 to-amber-50',
      border: '#EDE8D9',
    },
    dark: {
      primary: '#CFBC85',
      accent: '#2E2819',
      background: '#1A1810',
      text: '#F5EED9',
      gradient: 'from-slate-900 to-amber-950',
      border: '#3D3525',
    },
  },
  hobbies: {
    name: 'Hobbies',
    light: {
      primary: '#C97B6E',
      accent: '#FDF4F2',
      background: '#FCF8F7',
      text: '#4A322E',
      gradient: 'from-slate-50 to-rose-50',
      border: '#EDDDDA',
    },
    dark: {
      primary: '#D49588',
      accent: '#2E221F',
      background: '#1A1514',
      text: '#F5E6E3',
      gradient: 'from-slate-900 to-rose-950',
      border: '#3D2E2B',
    },
  },
  fitness: {
    name: 'Fitness',
    light: {
      primary: '#C99A6B',
      accent: '#FDF6F0',
      background: '#FFFAF7',
      text: '#5C4033',
      gradient: 'from-stone-50 to-amber-50',
      border: '#EDE6E0',
    },
    dark: {
      primary: '#D4A574',
      accent: '#2A2119',
      background: '#1A1612',
      text: '#F5EBE0',
      gradient: 'from-stone-900 to-amber-950',
      border: '#3D3428',
    },
  },
};

export const defaultTheme = themeConfig.default;

/** Sub-goals for each main goal. "custom" triggers a free-text input. */
export const subGoalsByMainGoal = {
  default: [
    { value: 'general', label: 'General focus' },
    { value: 'tasks', label: 'Task completion' },
    { value: 'custom', label: 'Custom…' },
  ],
  studies: [
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'science', label: 'Science' },
    { value: 'programming', label: 'Programming' },
    { value: 'languages', label: 'Languages' },
    { value: 'exams', label: 'Exam prep' },
    { value: 'research', label: 'Research' },
    { value: 'custom', label: 'Custom…' },
  ],
  work: [
    { value: 'meetings', label: 'Meetings' },
    { value: 'emails', label: 'Emails' },
    { value: 'projects', label: 'Project work' },
    { value: 'coding', label: 'Coding' },
    { value: 'reporting', label: 'Reporting' },
    { value: 'planning', label: 'Planning' },
    { value: 'custom', label: 'Custom…' },
  ],
  workout: [
    { value: 'cardio', label: 'Cardio' },
    { value: 'strength', label: 'Strength' },
    { value: 'hiit', label: 'HIIT' },
    { value: 'yoga', label: 'Yoga' },
    { value: 'stretching', label: 'Stretching' },
    { value: 'custom', label: 'Custom…' },
  ],
  health: [
    { value: 'sleep', label: 'Sleep' },
    { value: 'nutrition', label: 'Nutrition' },
    { value: 'mental', label: 'Mental health' },
    { value: 'hydration', label: 'Hydration' },
    { value: 'custom', label: 'Custom…' },
  ],
  meditation: [
    { value: 'mindfulness', label: 'Mindfulness' },
    { value: 'breathing', label: 'Breathing' },
    { value: 'visualization', label: 'Visualization' },
    { value: 'custom', label: 'Custom…' },
  ],
  skillimprovement: [
    { value: 'programming', label: 'Programming' },
    { value: 'design', label: 'Design' },
    { value: 'marketing', label: 'Marketing' },
    { value: 'languages', label: 'Languages' },
    { value: 'course', label: 'Online course' },
    { value: 'custom', label: 'Custom…' },
  ],
  reading: [
    { value: 'fiction', label: 'Fiction' },
    { value: 'nonfiction', label: 'Non-fiction' },
    { value: 'technical', label: 'Technical' },
    { value: 'articles', label: 'Articles' },
    { value: 'custom', label: 'Custom…' },
  ],
  creative: [
    { value: 'writing', label: 'Writing' },
    { value: 'design', label: 'Design' },
    { value: 'music', label: 'Music' },
    { value: 'art', label: 'Art' },
    { value: 'video', label: 'Video' },
    { value: 'custom', label: 'Custom…' },
  ],
  wellness: [
    { value: 'selfcare', label: 'Self-care' },
    { value: 'rest', label: 'Rest' },
    { value: 'journaling', label: 'Journaling' },
    { value: 'custom', label: 'Custom…' },
  ],
  personaldevelopment: [
    { value: 'goals', label: 'Goal setting' },
    { value: 'habits', label: 'Habits' },
    { value: 'communication', label: 'Communication' },
    { value: 'leadership', label: 'Leadership' },
    { value: 'custom', label: 'Custom…' },
  ],
  sociallife: [
    { value: 'family', label: 'Family' },
    { value: 'friends', label: 'Friends' },
    { value: 'networking', label: 'Networking' },
    { value: 'custom', label: 'Custom…' },
  ],
  hobbies: [
    { value: 'gaming', label: 'Gaming' },
    { value: 'crafts', label: 'Crafts' },
    { value: 'photography', label: 'Photography' },
    { value: 'cooking', label: 'Cooking' },
    { value: 'custom', label: 'Custom…' },
  ],
  fitness: [
    { value: 'cardio', label: 'Cardio' },
    { value: 'strength', label: 'Strength' },
    { value: 'flexibility', label: 'Flexibility' },
    { value: 'custom', label: 'Custom…' },
  ],
};

export const goals = [
  { key: 'studies', name: 'Studies', emoji: '📚', color: 'blue' },
  { key: 'work', name: 'Work', emoji: '💼', color: 'violet' },
  { key: 'workout', name: 'Workout', emoji: '🏃', color: 'orange' },
  { key: 'health', name: 'Health', emoji: '💚', color: 'emerald' },
  { key: 'meditation', name: 'Meditation', emoji: '🧘', color: 'teal' },
  { key: 'skillimprovement', name: 'Skill Improvement', emoji: '🚀', color: 'indigo' },
  { key: 'reading', name: 'Reading', emoji: '📖', color: 'sky' },
  { key: 'creative', name: 'Creative', emoji: '🎨', color: 'rose' },
  { key: 'wellness', name: 'Wellness', emoji: '💆', color: 'pink' },
  { key: 'personaldevelopment', name: 'Personal Development', emoji: '⭐', color: 'purple' },
  { key: 'sociallife', name: 'Social Life', emoji: '👥', color: 'yellow' },
  { key: 'hobbies', name: 'Hobbies', emoji: '🎯', color: 'coral' },
];

/** Vast color palette for custom theme (primary) – saved to user account only */
export const themeColorPalette = [
  '#5B8DEF', '#6B8BD4', '#7C9BED', '#8B7DB8', '#9F8FCF', '#6B9B8A', '#7DB39D', '#6B9A9A', '#7DB5B5',
  '#7B7FC4', '#8F93D4', '#6B8FB8', '#7DA5D4', '#B87B8A', '#C995A3', '#B87A9E', '#CB9AB5', '#9A7FB8',
  '#B09AD4', '#B8A06B', '#CFBC85', '#C97B6E', '#D49588', '#C99A6B', '#D4A574', '#E07B6B', '#E89588',
  '#4A7BD4', '#5A8BE8', '#6A9BF4', '#9B6DB8', '#AB8DCF', '#5B9B7A', '#6BAB8D', '#5B8A8A', '#6BAAAE',
  '#6B6FC4', '#7B83D4', '#5B7FA8', '#6B9BC8', '#A86B7A', '#B88B98', '#A86A8E', '#B88AA8', '#8A6FA8',
  '#9A8BC8', '#A8905B', '#B8A075', '#B86B5E', '#C88B80', '#B88A5B', '#C89A74', '#D04A3B', '#D86A5C',
  '#3A6BC4', '#4A7BE8', '#5A8BF4', '#8B5DA8', '#9B7DC4', '#4B8B6A', '#5B9B8A', '#4B7A7A', '#5B9A9E',
  '#5B5FB4', '#6B73C8', '#4B6F98', '#5B8BB8', '#985B6A', '#A87B88', '#985A7E', '#A87A98', '#7A5F98',
  '#8A7BB8', '#98704B', '#A89065', '#985B4E', '#B87B70', '#987A4B', '#A88A64', '#C03A2B', '#C85A4C',
  '#2A5BB4', '#3A6BD8', '#4A7BE4', '#7B4D98', '#8B6DB4', '#3B7B5A', '#4B8B7A', '#3B6A6A', '#4B8A8E',
  '#4B4FA4', '#5B63B8', '#3B5F88', '#4B7BA8', '#884B5A', '#986B78', '#884A6E', '#986A88', '#6A4F88',
  '#7A6BA8', '#88603B', '#988050', '#884B3E', '#A86B60', '#886A3B', '#987A54', '#B02A1B', '#B84A3C',
  '#6D8EFF', '#7D9EFF', '#5E7BC9', '#8E6EC5', '#AE8ED8', '#5E9E7E', '#6EAE9E', '#5E8E8E', '#6EAEAE',
  '#6E72D4', '#7E82E4', '#5E82B8', '#6E9ED8', '#BE6E7E', '#CE8E9E', '#BE5E8E', '#CE7EAE', '#9E72CE',
  '#AE92DE', '#AE8262', '#BE9272', '#CE6262', '#DE8282', '#CE8262', '#DE9282', '#EF5252', '#E77272',
  '#4D6EDE', '#5D7EEE', '#8D5EB8', '#9D7EC8', '#4D8E6E', '#5D9E8E', '#4D7E7E', '#5D9E9E', '#5D61C4',
  '#6D71D4', '#4D72A8', '#5D8EC8', '#AD5D6E', '#BD7D8E', '#AD4D7E', '#BD6D9E', '#8D61BE', '#9D81CE',
  '#9D714D', '#AD816D', '#BD5152', '#CD7172', '#BD714D', '#CD8162', '#DD4142', '#D56162',
  '#7B5ECA', '#8B6EDA', '#6B8EAA', '#9B5E9A', '#AB7EAA', '#5B9E7B', '#6BAE9B', '#5B8E8E', '#6BAEAE',
  '#6B6FC8', '#7B7FD8', '#5B82B2', '#6B9EC2', '#BB6B7B', '#CB8B9B', '#BB5B8B', '#CB7BAB', '#9B6FC2',
  '#AB8FD2', '#AB7F5B', '#BB8F6B', '#CB5B5C', '#DB7B7C', '#CB7B5B', '#DB8B6C', '#EB4B4C', '#DB6B6C',
  '#5B4EBA', '#6B5ECA', '#4B7E9A', '#8B4E8A', '#9B6E9A', '#4B8E6B', '#5B9E8B', '#4B7E7E', '#5B9E9E',
  '#5B5FB8', '#6B6FC8', '#4B72A2', '#5B8EB2', '#AB5B6B', '#BB7B8B', '#AB4B7B', '#BB6B9B', '#8B5FB2',
  '#9B7FC2', '#9B6F4B', '#AB7F5B', '#BB4B4C', '#CB6B6C', '#BB6B4B', '#CB7B5C', '#DB3B3C', '#CB5B5C',
  '#8A9EFF', '#9AAEFF', '#6A8BD9', '#AA7ED9', '#CA9EE9', '#6AAE8E', '#7ABEAE', '#6A9E9E', '#7ABEBE',
  '#7A7EE4', '#8A8EF4', '#6A92C8', '#7AAED8', '#CE7E8E', '#DE9EAE', '#CE6E9E', '#DE8EAE', '#AE82DE',
  '#BEA2EE', '#BE926A', '#CEA27A', '#DE6A6A', '#EE8A8A', '#DE8A6A', '#EE9A8A', '#FE5A5A', '#EE7A7A',
  '#6B5ED8', '#7B6EE8', '#5B8EC8', '#9B5E98', '#AB7EA8', '#5B9E7E', '#6BAE9E', '#5B8E8E', '#6BAEAE',
  '#6B6FD8', '#7B7FE8', '#5B82B8', '#6B9EC8', '#BD6B7E', '#CD8B9E', '#BD5B8E', '#CD7BAE', '#9B6FD8',
  '#AB8FE8', '#AB7F5B', '#BB8F6B', '#CB5B5C', '#DB7B7C', '#CB7B5B', '#DB8B6C', '#EB4B4C', '#DB6B6C',
];
